name: ACL2020
tagline: 2020 Annual Conference of the Association for Computational Linguistics
date: July 2020
proceedings_title: Proceedings of the First MiniCon Conference
analytics: UA-
logo:
  image: static/images/acl-logo.png
  height: 45px
site_title: ACL2020
page_title:
  prefix: 'ACL2020'
  separator: ': '
background_image: static/images/unsplash.jpg
organization: Association for Computational Linguistics
calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday
