name: 2020 Annual Conference of the Association for Computational Linguistics
tagline: 2020 Annual Conference of the Association for Computational Linguistics
data: July 2020
analytics: UA-
logo: static/images/acl-logo.png
title: ACL2020
organization: Association for Computational Linguistics
calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday

