name: MiniConf
tagline: MINICONF <br> CONFERENCE <br> MANAGEMENT
data: May 2020
analytics: UA-
logo: static/images/acl-logo.png
title: ACL2020
organization:
calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday

