name: ACL
tagline: 2020 Annual Conference of the Association for Computational Linguistics
data: July 2020
analytics: UA-
logo:
  image: static/images/acl-logo.png
  height: 45px
site_title: ACL2020
background_image: static/images/unsplash.jpg
organization: Association for Computational Linguistics
calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday

